### ISSUE TITLE
[Off-topic] Bus driver sim app

### ISSUE THREAD

**Issue by daguar** [openoakland/oakland-transit-data#2]
Heyo! Thought y'all might enjoy a current CfA fellow (@jden)'s bus driver simulation app:
http://jden.us/bus-sim/

The source code is here:
https://github.com/jden/bus-sim

**Comment by spjika** [comment]
That's gonna break the internets if a nightly news channel every broadcasts
the link!

Spike
openoakland.org
www.stealingbeautyphotography.com

**Comment by max-mapper** [comment]
quick and dirty ACTransit version :)
http://openoakland.github.io/bus-sim/(takes a minute to load
initially)

**Comment by junosuarez** [comment]
This issue is still showing up on my personal "[open issues mentioning you](https://github.com/issues/mentioned)" list, limiting its utility. Could you please consider closing it?
